- name: stop easydb5-server
  command: docker stop easydb-server
  failed_when: no
  #ignore_errors: yes

  #docker_container:
  #  name: "easydb-server"
  #  state: started
  #  restart: yes
  #  ignore_image: yes
