---
dependency:
  name: galaxy
driver:
  name: vagrant
  safe_files:
    - .molecule
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: stretch
    box: bento/debian-9
    memory: 2048
    # memory is given in MB
    #cpus: 2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
