---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: stretch
    box: bento/debian-9
    memory: 3072  # memory is given in MB
    #memory: 2048  # memory is given in MB
provisioner:
  name: ansible
  connection_options:
    ansible_become: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
