---
- name: Converge
  hosts: all
  become: yes
  vars:
    docker_enabled: yes
    easydb_url: http://localhost:8080
    easydb_customer_id: be52ae33594eb794828ccd4837cf08ae
    easydb_solution: base
    easydb_docker_user: ci
    easydb_docker_pass: '82VK#nUQ7='

  roles:
    - role: role-easydb5
