- name: configuring easydb update as cron job
  template:
    src: etc/cron.d/easydb5-update
    dest: /etc/cron.d/easydb5-update
    owner: root
    group: root
    mode: 0644

- name: removing old central cron file
  file:
    path: /etc/cron.d/easydb5
    state: absent

- name: configuring logrotation
  template:
    src: etc/logrotate.d/easydb
    dest: /etc/logrotate.d/easydb
    owner: root
    group: root
    mode: 0644
